plugins {
    id 'dev.architectury.loom' version '1.13-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id "me.modmuss50.mod-publish-plugin" version "1.0.0"
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'
    apply plugin: 'me.modmuss50.mod-publish-plugin'

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$rootProject.yarn_mappings:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$rootProject.yarn_mappings_patch_neoforge_version")
        }
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    def modLoader = name
    def changelogText = rootProject.file("CHANGELOG.md").text
    def supportedVersions = rootProject.findProperty("supported_versions")
            .split(",")
            .collect { it.trim() }

    if (project.name != "common") {
        publishMods {
            changelog = changelogText
            file.set(tasks.remapJar.archiveFile)
            additionalFiles.from(tasks.remapSourcesJar.archiveFile)
            displayName = project.mod_name + " " + project.mod_version + "-$modLoader"
            version = project.mod_version + "-$modLoader"
            type = project.mod_version.contains("beta") ? BETA : STABLE
            if (modLoader == "fabric") {
                modLoaders.add("fabric")
                modLoaders.add("quilt")
            } else if (modLoader == "neoforge") {
                modLoaders.add("neoforge")
            }
            dryRun = providers.environmentVariable("MODRINTH_TOKEN").getOrNull() == null ||
                    providers.environmentVariable("CURSEFORGE_TOKEN").getOrNull() == null
            modrinth {
                projectId = "XnLNz8og"
                accessToken = providers.environmentVariable("MODRINTH_TOKEN")
                minecraftVersions.set(supportedVersions.unique())
                if (modLoader == "fabric") {
                    requires("fabric-api")
                }
            }
            curseforge {
                projectId = "1216837"
                changelogType = "markdown"
                accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
                minecraftVersions.set(supportedVersions.unique())
                javaVersions.set([JavaVersion.VERSION_21])
                clientRequired = true
                serverRequired = true
                projectSlug = "macu-lib"
                if (modLoader == "fabric") {
                    requires("fabric-api")
                }
            }
        }
    }
}