org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=macu_lib
mod.name=macu Lib
mod.group=com.macuguita
mod.version=2.0.2

deps.fabric-loader=0.18.4
deps.kaleido=0.3.3+1.3.2

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=XnLNz8og
publish.curseforge=1216837
#publish.additionalVersions=
