modLoader = "javafml"
loaderVersion = "[2,)"
license = "EUPL-1.2"
issueTrackerURL = "https://github.com/macuguita/macu_lib/issues"

[[mods]]
modId = "macu_lib"
version = "${version}"
displayName = "macu Lib"
description = '''Common library for my mods'''
authors = "macuguita"
logoFile = "assets/icon.png"
logoBlur = false
displayURL = "https://macuguita.com"
issueTrackerURL = "https://github.com/macuguita/macu_lib/issues"
updateJSONURL = "https://api.modrinth.com/updates/XnLNz8og/forge_updates.json?neoforge=only"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "macu_lib.mixins.json"

[[dependencies.macu_lib]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.macu_lib]]
modId = "yumi_mc_core"
type = "required"
versionRange = "[${yumi_version},)"
ordering = "NONE"
side = "CLIENT"

[modproperties.macu_lib]
catalogueImageIcon = "assets/icon.png"


[modproperties.yumi_mc_core_testmod."yumi:entrypoints"]
"yumi:init" = ["com.macuguita.lib.impl.MacuLib", "com.macuguita.lib.impl.persista.Persista"]
"yumi:client_init" = ["com.macuguita.lib.impl.client.MacuLibClient", "com.macuguita.lib.impl.persista.PersistaClient"]
