[versions]
minecraft = "26.1.2"

fabric-loader = "0.19.2"
fabric-api = "0.149.1+26.1.2"

neoforge = "26.1.2.66-beta"
neoforge-loader = "11.0.0"

yumi = "1.0.1+26.1"
kaleido = "0.3.3+1.3.2"

mod = "3.0.0"

spotless = "8.5.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }

yumi-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi" }

kaleido-config = { module = "folk.sisby:kaleido-config", version.ref = "kaleido" }

modmenu = { module = "com.terraformersmc:modmenu", version = "18.0.0-beta.1" }

gradle-loom = { module = "fabric-loom:fabric-loom.gradle.plugin", version = "1.16.+" }
gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
dotenv = { id = "co.uzzu.dotenv.gradle", version = "4.0.0" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version = "2.0.0-beta.1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
