modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/macuguita/macu_lib"
license = "${license}"

[[mods]]
modId = "macu_lib"
version = "${version}-neoforge"
displayName = "macu lib"
authors = "macuguita"
description = '''
Library for my mods and adding supporter perks
'''
displayURL="https://macuguita.com"
logoFile = "assets/macu_lib/logo.png"

[[mixins]]
config="macu_lib.mixins.json"

[[dependencies.macu_lib]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.macu_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"
